#!/bin/bash

# Build a docker image for the Aedes ISV VT reproducible paper
# 
# MDS 8/2026


echo "must login to GHCR before running these commands; see README.md"

# build image
docker buildx build --platform linux/amd64 -t ghcr.io/stenglein-lab/aedes_isv_vt:1.0 .

# push image
docker push ghcr.io/stenglein-lab/aedes_isv_vt:1.0

